esphome:
  name: node1

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "sanwenjing@163.com"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: !secret ap_ssid
    password: !secret ap_password

captive_portal:


web_server:
  port: 80
  auth:
    username: admin
    password: admin

mqtt:
  broker: !secret broker_server
  username: !secret mqtt_username
  password: !secret mqtt_password

switch:
  - platform: gpio
    pin: GPIO0
    name: "wireless_switch02"
    id: relay2
    inverted: true
    
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO2
      inverted: true
    name: "light"
    device_class: opening
    filters:
      - delayed_on: 10ms
      - delayed_off: 10ms
